export const defaultResumeData = {
  title: "Untitled Resume",
  templateId: "classic",
  personalInfo: {
    fullName: "",
    email: "",
    phone: "",
    address: "",
    jobTitle: "",
  },
  summary: "",
  education: [],
  experience: [],
  skills: [],
  projects: [],
  certifications: [],
  languages: [],
  socialLinks: [],
  themeColors: {
    primary: "#235a7e",
    primaryHover: "#1b4a65",
    accent: "#f0a845",
    bg: "#eef4f9",
    surface: "#ffffff",
    border: "#d7e1e9",
  },
};